### ISSUE TITLE
✅Feature:그룹 채팅 생성, 참여 구현

### ISSUE THREAD

**Issue by lsy28901** [08month-team-project/runto_BE#9]
## Description
그룹(모임) 채팅을 생성합니다.

## Todo

- [ ] GroupChatService 에서 그룹 채팅 생성 구현
- [ ] GroupChatRoomRepository 생성 (JPA)
- [ ] GroupChatRoomUserRepository 생성 (JPA)
- [ ] GroupChatRoom 엔티티 구현
- [ ] GroupChatRoomUser 엔티티 구현
- [ ] GroupChatService 에서 그룹 채팅 참여 구현
